version: "3.9"
services:
  analytics-backend:
    container_name: analytics-backend
    build:
      context: .
    ports:
      - "2020:2020"
    restart: always
    networks:
      - analytics-network

networks:
  analytics-network:
    driver: bridge
